import { Customer, AirEquipment, Technician, ServiceOrder, AirPart, AirSettings } from '../types';
import { subMonths, addDays, format } from 'date-fns';

const today = new Date();

export const INITIAL_SETTINGS: AirSettings = {
  company_name: 'Nexus Air Climatización SpA',
  fantasy_name: 'Nexus Air',
  rut: '77.890.123-K',
  phone: '+56 9 8765 4321',
  whatsapp_number: '+56987654321',
  email: 'contacto@nexusair.cl',
  address: 'Av. Las Condes 10450, Of. 402',
  commune: 'Las Condes',
  website: 'https://nexusair.cl',
  maintenance_interval_months: 6, // Clave: Recaptación semestral cada 6 meses
  standard_maintenance_price: 45000,
  standard_installation_price: 130000,
  whatsapp_template_recaptacion: 'Hola {cliente}, te saludamos de Nexus Air. Tu equipo de aire acondicionado {marca} ({btu} BTU) instalado en {ubicacion} está cumpliendo 6 meses desde su última mantención preventiva. Para asegurar aire puro, evitar malos olores y optimizar el consumo eléctrico para esta temporada, te invitamos a agendar con tu técnico asignado aquí: {link}',
  whatsapp_template_agendamiento: 'Estimado/a {cliente}, tu servicio técnico para {tipo_servicio} ha sido programado para el día {fecha} en el bloque {hora}. El técnico asignado es {tecnico}.',
  whatsapp_template_terminado: 'Estimado/a {cliente}, el servicio de {tipo_servicio} para tu equipo {marca} ha finalizado con éxito. Tu salto térmico medido fue de {delta_t}°C y presiones en norma. Tu próxima mantención preventiva está programada para dentro de 6 meses ({proxima_fecha}). ¡Gracias por confiar en Nexus Air!',
};

export const INITIAL_TECHNICIANS: Technician[] = [
  {
    id: 'tech-1',
    name: 'Juan Pablo Morales',
    rut: '16.452.981-3',
    phone: '+56 9 9123 4567',
    email: 'j.morales@nexusair.cl',
    sec_certified: true,
    certification_number: 'SEC-HVAC-8842',
    status: 'en_servicio',
    active_orders_count: 2,
  },
  {
    id: 'tech-2',
    name: 'Rodrigo Araya Silva',
    rut: '17.821.340-9',
    phone: '+56 9 8234 5678',
    email: 'r.araya@nexusair.cl',
    sec_certified: true,
    certification_number: 'SEC-HVAC-9104',
    status: 'disponible',
    active_orders_count: 1,
  },
  {
    id: 'tech-3',
    name: 'Camilo Henríquez Vera',
    rut: '18.112.567-4',
    phone: '+56 9 7345 6789',
    email: 'c.henriquez@nexusair.cl',
    sec_certified: true,
    certification_number: 'SEC-HVAC-7330',
    status: 'disponible',
    active_orders_count: 1,
  },
];

export const INITIAL_EQUIPMENTS: AirEquipment[] = [
  {
    id: 'eq-1',
    customer_id: 'cust-1',
    brand: 'Anwo',
    model: 'Eco Inverter V-Series',
    serial_number: 'ANW-2024-99812',
    btu: 12000,
    type: 'split_muro',
    technology: 'inverter',
    refrigerant: 'R410A',
    location_in_property: 'Living Comedor',
    installation_date: format(subMonths(today, 13), 'yyyy-MM-dd'),
    last_maintenance_date: format(subMonths(today, 6.5), 'yyyy-MM-dd'), // Vencido (> 6 meses)
    next_maintenance_date: format(addDays(subMonths(today, 6.5), 180), 'yyyy-MM-dd'),
    notes: 'Requiere limpieza química de turbina profunda y verificación de bandeja de condensado.',
  },
  {
    id: 'eq-2',
    customer_id: 'cust-2',
    brand: 'Midea',
    model: 'Breezeless Inverter Pro',
    serial_number: 'MID-2025-11029',
    btu: 18000,
    type: 'split_muro',
    technology: 'inverter',
    refrigerant: 'R32',
    location_in_property: 'Oficina Central / Sala de Juntas',
    installation_date: format(subMonths(today, 8), 'yyyy-MM-dd'),
    last_maintenance_date: format(subMonths(today, 5.7), 'yyyy-MM-dd'), // Por vencer (queda < 10 días para 6 meses)
    next_maintenance_date: format(addDays(subMonths(today, 5.7), 180), 'yyyy-MM-dd'),
    notes: 'Equipo con gas ecológico R32. Monitorear presión de trabajo en 125 PSI.',
  },
  {
    id: 'eq-3',
    customer_id: 'cust-3',
    brand: 'Daikin',
    model: 'Sensira EcoComfort',
    serial_number: 'DAI-2025-77821',
    btu: 9000,
    type: 'split_muro',
    technology: 'inverter',
    refrigerant: 'R32',
    location_in_property: 'Dormitorio Principal',
    installation_date: format(subMonths(today, 2), 'yyyy-MM-dd'),
    last_maintenance_date: format(subMonths(today, 2), 'yyyy-MM-dd'), // Al día
    next_maintenance_date: format(addDays(subMonths(today, 2), 180), 'yyyy-MM-dd'),
    notes: 'Instalación nueva con bomba de vacío de doble etapa y presurización con nitrógeno.',
  },
  {
    id: 'eq-4',
    customer_id: 'cust-4',
    brand: 'Gree',
    model: 'U-Crown 4-Way Cassette',
    serial_number: 'GRE-2024-55410',
    btu: 24000,
    type: 'cassette',
    technology: 'inverter',
    refrigerant: 'R410A',
    location_in_property: 'Local Comercial Planta Libre',
    installation_date: format(subMonths(today, 15), 'yyyy-MM-dd'),
    last_maintenance_date: format(subMonths(today, 7.2), 'yyyy-MM-dd'), // Críticamente vencido (> 7 meses)
    next_maintenance_date: format(addDays(subMonths(today, 7.2), 180), 'yyyy-MM-dd'),
    notes: 'Filtros con acumulación de grasa ambiental y polvo en suspensión.',
  },
  {
    id: 'eq-5',
    customer_id: 'cust-1',
    brand: 'Clark',
    model: 'HighWall Eco 9k',
    serial_number: 'CLK-2023-44120',
    btu: 9000,
    type: 'split_muro',
    technology: 'inverter',
    refrigerant: 'R410A',
    location_in_property: 'Dormitorio Visitas',
    installation_date: format(subMonths(today, 18), 'yyyy-MM-dd'),
    last_maintenance_date: format(subMonths(today, 5.8), 'yyyy-MM-dd'), // Por vencer
    next_maintenance_date: format(addDays(subMonths(today, 5.8), 180), 'yyyy-MM-dd'),
    notes: 'Ubicado en 2do piso, condensador exterior accesible por balcón.',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Carolina Baeza Donoso',
    rut: '15.340.291-8',
    phone: '+56 9 9876 5432',
    email: 'cbaeza@gmail.com',
    address: 'Av. Vitacura 4520, Depto 601',
    commune: 'Vitacura',
    city: 'Santiago',
    customer_type: 'residencial',
    notes: 'Conserjería 24 hrs. Estacionamiento de visitas subterráneo.',
    created_at: format(subMonths(today, 14), 'yyyy-MM-dd'),
  },
  {
    id: 'cust-2',
    name: 'Inversiones & Cowork El Golf Ltda',
    rut: '76.459.882-1',
    phone: '+56 9 8765 1234',
    email: 'administracion@elgolfcowork.cl',
    address: 'Apoquindo 3000, Piso 8',
    commune: 'Las Condes',
    city: 'Santiago',
    customer_type: 'comercial',
    notes: 'Horario preferente para mantenciones: después de las 18:00 hrs o sábados por la mañana.',
    created_at: format(subMonths(today, 9), 'yyyy-MM-dd'),
  },
  {
    id: 'cust-3',
    name: 'Matías Valenzuela Lagos',
    rut: '16.920.441-K',
    phone: '+56 9 7654 3210',
    email: 'm.valenzuela@gmail.com',
    address: 'Suecia 1845, Casa 4',
    commune: 'Providencia',
    city: 'Santiago',
    customer_type: 'residencial',
    notes: 'Mascotas en el patio. Avisar 15 minutos antes de llegar.',
    created_at: format(subMonths(today, 3), 'yyyy-MM-dd'),
  },
  {
    id: 'cust-4',
    name: 'Restobar & Café La Casona',
    rut: '77.102.833-4',
    phone: '+56 9 6543 2109',
    email: 'lacasona.rest@gmail.com',
    address: 'Av. Italia 1250',
    commune: 'Ñuñoa',
    city: 'Santiago',
    customer_type: 'comercial',
    notes: 'Salón principal con alta afluencia de comensales. Mantención clave de filtros y evaporador.',
    created_at: format(subMonths(today, 16), 'yyyy-MM-dd'),
  },
];

export const INITIAL_PARTS: AirPart[] = [
  {
    id: 'part-1',
    sku: 'EQ-ANW-12K-INV',
    name: 'Aire Acondicionado Split Anwo 12.000 BTU Inverter A++',
    category: 'equipo',
    brand: 'Anwo',
    btu: 12000,
    stock: 14,
    min_stock: 4,
    cost_price: 245000,
    sale_price: 349990,
    unit: 'unidad',
    description: 'Equipo alta eficiencia energética A++, refrigerante ecológico R410A/R32, modo frío y calor, control remoto y WiFi Ready.',
  },
  {
    id: 'part-2',
    sku: 'EQ-MID-18K-INV',
    name: 'Aire Acondicionado Split Midea Breezeless 18.000 BTU Inverter',
    category: 'equipo',
    brand: 'Midea',
    btu: 18000,
    stock: 8,
    min_stock: 2,
    cost_price: 380000,
    sale_price: 529990,
    unit: 'unidad',
    description: 'Tecnología Breezeless con 7.928 microorificios para enfriamiento suave sin ráfagas directas. Gas R32.',
  },
  {
    id: 'part-3',
    sku: 'EQ-DAI-09K-INV',
    name: 'Aire Acondicionado Daikin Sensira 9.000 BTU Inverter',
    category: 'equipo',
    brand: 'Daikin',
    btu: 9000,
    stock: 10,
    min_stock: 3,
    cost_price: 260000,
    sale_price: 369990,
    unit: 'unidad',
    description: 'Silencioso (19 dBA), ideal para dormitorios. Alta eficiencia japonesa.',
  },
  {
    id: 'part-4',
    sku: 'INS-GAS-R410A',
    name: 'Balón Gas Refrigerante R410A 11.3 Kg',
    category: 'refrigerante',
    brand: 'Chemours / Dupont',
    stock: 12,
    min_stock: 3,
    cost_price: 95000,
    sale_price: 155000,
    unit: 'unidad',
    description: 'Gas ecológico HFC para sistemas de climatización split y multisplit.',
  },
  {
    id: 'part-5',
    sku: 'INS-GAS-R32',
    name: 'Balón Gas Refrigerante R32 9.5 Kg',
    category: 'refrigerante',
    brand: 'Forane',
    stock: 9,
    min_stock: 3,
    cost_price: 110000,
    sale_price: 175000,
    unit: 'unidad',
    description: 'Refrigerante de última generación, bajo GWP, mayor rendimiento termodinámico.',
  },
  {
    id: 'part-6',
    sku: 'INS-COBRE-KIT',
    name: 'Kit de Cañería de Cobre 1/4" y 3/8" x 3 Metros con Aislación',
    category: 'cobre_aislacion',
    brand: 'Nacional Cobre',
    stock: 35,
    min_stock: 10,
    cost_price: 24000,
    sale_price: 45000,
    unit: 'kit',
    description: 'Tuberías con aislación térmica blanca elastomérica resistente a rayos UV para interconexión.',
  },
  {
    id: 'part-7',
    sku: 'INS-BOMBA-COND',
    name: 'Bomba de Condensado Silenciosa Mini Orange Aspen',
    category: 'bomba_soporte',
    brand: 'Aspen Pumps',
    stock: 7,
    min_stock: 2,
    cost_price: 52000,
    sale_price: 89000,
    unit: 'unidad',
    description: 'Bomba automática para evacuación de agua de condensado en muros interiores sin caída libre.',
  },
  {
    id: 'part-8',
    sku: 'INS-QUIM-SAN',
    name: 'Sanitizante & Bactericida HVAC ClimaClean 5 Litros',
    category: 'quimico',
    brand: 'ClimaCare Pro',
    stock: 18,
    min_stock: 5,
    cost_price: 16000,
    sale_price: 28000,
    unit: 'litro',
    description: 'Elimina hongos, ácaros, bacterias y olores en serpentines y bandejas de condensado.',
  },
];

export const INITIAL_SERVICE_ORDERS: ServiceOrder[] = [
  {
    id: 'ord-1',
    ticket_number: 'AIR-2026-001',
    customer_id: 'cust-1',
    equipment_id: 'eq-1',
    service_type: 'mantencion_preventiva',
    status: 'en_proceso',
    scheduled_date: format(today, 'yyyy-MM-dd'),
    scheduled_time_slot: '09:30 - 11:30',
    assigned_technician_id: 'tech-1',
    description: 'Mantención preventiva semestral de 6 meses. Limpieza química de serpentín interior, revisión de salto térmico y presurización.',
    diagnosis: 'Filtros con acumulación de polvo al 70%. Condensador exterior con buen tiro pero requiere desincrustado de aletas.',
    checklist: {
      clean_evaporator_coil: true,
      clean_turbine_fan: true,
      sanitize_bactericide: true,
      clean_condenser_coil: false,
      check_electrical_connections: true,
      check_condensate_drain: true,
      clean_filters: true,
      delta_t_celsius: 12.5,
      suction_pressure_psi: 120,
      amperage_amps: 4.8,
      technician_notes: 'Equipo operando estable. Se aplicó bactericida con aroma menta fresca.',
    },
    items: [
      { id: 'it-1', description: 'Servicio Mantención Preventiva Split 12k BTU', quantity: 1, unit_price: 45000, total: 45000, type: 'servicio' },
      { id: 'it-2', description: 'Sanitización profunda con bactericida HVAC', quantity: 1, unit_price: 10000, total: 10000, type: 'insumo' },
    ],
    subtotal: 55000,
    tax: 10450,
    total: 65450,
    payment_status: 'pendiente',
    created_at: format(today, 'yyyy-MM-dd HH:mm'),
  },
  {
    id: 'ord-2',
    ticket_number: 'AIR-2026-002',
    customer_id: 'cust-3',
    service_type: 'instalacion',
    status: 'en_ruta',
    scheduled_date: format(today, 'yyyy-MM-dd'),
    scheduled_time_slot: '12:00 - 15:00',
    assigned_technician_id: 'tech-2',
    description: 'Instalación nueva de Split Muro Anwo 12.000 BTU Inverter en Dormitorio Secundario. Incluye perforación de muro, soporte de exterior y vacío.',
    checklist: {
      clean_evaporator_coil: false,
      clean_turbine_fan: false,
      sanitize_bactericide: false,
      clean_condenser_coil: false,
      check_electrical_connections: false,
      check_condensate_drain: false,
      clean_filters: false,
    },
    items: [
      { id: 'it-3', description: 'Aire Acondicionado Split Anwo 12.000 BTU Inverter A++', quantity: 1, unit_price: 349990, total: 349990, type: 'equipo' },
      { id: 'it-4', description: 'Instalación Básica hasta 3 metros de cañería con vacío', quantity: 1, unit_price: 130000, total: 130000, type: 'servicio' },
      { id: 'it-5', description: 'Soporte metálico reforzado para unidad exterior', quantity: 1, unit_price: 18000, total: 18000, type: 'insumo' },
    ],
    subtotal: 497990,
    tax: 94618,
    total: 592608,
    payment_status: 'abono',
    created_at: format(today, 'yyyy-MM-dd HH:mm'),
  },
  {
    id: 'ord-3',
    ticket_number: 'AIR-2026-003',
    customer_id: 'cust-4',
    equipment_id: 'eq-4',
    service_type: 'mantencion_correctiva',
    status: 'ingresado',
    scheduled_date: format(addDays(today, 1), 'yyyy-MM-dd'),
    scheduled_time_slot: '10:00 - 12:00',
    assigned_technician_id: 'tech-3',
    description: 'Cassette 24k en local comercial no enfría suficiente y bota algunas gotas de agua en la rejilla difusora.',
    diagnosis: 'Posible obstrucción en trampa de drenaje o micro-fuga de refrigerante R410A.',
    checklist: {
      clean_evaporator_coil: false,
      clean_turbine_fan: false,
      sanitize_bactericide: false,
      clean_condenser_coil: false,
      check_electrical_connections: false,
      check_condensate_drain: false,
      clean_filters: false,
    },
    items: [
      { id: 'it-6', description: 'Visita de Diagnóstico Técnico y Reparación HVAC', quantity: 1, unit_price: 35000, total: 35000, type: 'servicio' },
    ],
    subtotal: 35000,
    tax: 6650,
    total: 41650,
    payment_status: 'pendiente',
    created_at: format(today, 'yyyy-MM-dd HH:mm'),
  },
  {
    id: 'ord-4',
    ticket_number: 'AIR-2026-004',
    customer_id: 'cust-2',
    equipment_id: 'eq-2',
    service_type: 'mantencion_preventiva',
    status: 'pruebas_qa',
    scheduled_date: format(today, 'yyyy-MM-dd'),
    scheduled_time_slot: '08:30 - 10:30',
    assigned_technician_id: 'tech-1',
    description: 'Mantención preventiva semestral en Cowork El Golf. Se realizó limpieza con hidrolavadora a presión controlada y prueba de temperatura.',
    diagnosis: 'Excelente estado estructural. Consumo eléctrico dentro de los parámetros de fabricante.',
    checklist: {
      clean_evaporator_coil: true,
      clean_turbine_fan: true,
      sanitize_bactericide: true,
      clean_condenser_coil: true,
      check_electrical_connections: true,
      check_condensate_drain: true,
      clean_filters: true,
      delta_t_celsius: 14.1,
      suction_pressure_psi: 128,
      amperage_amps: 6.2,
      technician_notes: 'Prueba de frío superada: inyección en 10.2°C con retorno en 24.3°C.',
    },
    items: [
      { id: 'it-7', description: 'Mantención Preventiva Split 18k BTU Inverter R32', quantity: 1, unit_price: 55000, total: 55000, type: 'servicio' },
    ],
    subtotal: 55000,
    tax: 10450,
    total: 65450,
    payment_status: 'pagado',
    payment_method: 'transferencia',
    created_at: format(today, 'yyyy-MM-dd HH:mm'),
  },
  {
    id: 'ord-5',
    ticket_number: 'AIR-2026-005',
    customer_id: 'cust-1',
    equipment_id: 'eq-5',
    service_type: 'mantencion_preventiva',
    status: 'completado',
    scheduled_date: format(subMonths(today, 1), 'yyyy-MM-dd'),
    scheduled_time_slot: '15:00 - 17:00',
    assigned_technician_id: 'tech-2',
    description: 'Mantención preventiva completada. Equipo con flujo de aire restaurado.',
    checklist: {
      clean_evaporator_coil: true,
      clean_turbine_fan: true,
      sanitize_bactericide: true,
      clean_condenser_coil: true,
      check_electrical_connections: true,
      check_condensate_drain: true,
      clean_filters: true,
      delta_t_celsius: 13.0,
      suction_pressure_psi: 118,
      amperage_amps: 3.9,
    },
    items: [
      { id: 'it-8', description: 'Mantención Preventiva Split 9k BTU Inverter', quantity: 1, unit_price: 40000, total: 40000, type: 'servicio' },
    ],
    subtotal: 40000,
    tax: 7600,
    total: 47600,
    payment_status: 'pagado',
    payment_method: 'tarjeta',
    created_at: format(subMonths(today, 1), 'yyyy-MM-dd'),
    completed_at: format(subMonths(today, 1), 'yyyy-MM-dd HH:mm'),
  },
];
